package com_spring_core9$16_data_sakila;
// Generated Aug 4, 2015 10:26:57 AM by Hibernate Tools 4.0.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import com_spring_core9$16_data_sakila.SalesByStoreId;

/**
 * SalesByStore generated by hbm2java
 */
@Entity
@Table(name="sales_by_store"
    ,catalog="sakila"
)
public class SalesByStore  implements java.io.Serializable {


     private SalesByStoreId id;

    public SalesByStore() {
    }

    public SalesByStore(SalesByStoreId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="store", column=@Column(name="store", length=101) ), 
        @AttributeOverride(name="manager", column=@Column(name="manager", length=91) ), 
        @AttributeOverride(name="totalSales", column=@Column(name="total_sales", precision=27) ) } )
    public SalesByStoreId getId() {
        return this.id;
    }
    
    public void setId(SalesByStoreId id) {
        this.id = id;
    }




}


