package com_spring_core9$16_data_test;

// Generated Aug 4, 2015 4:40:58 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Table1 generated by hbm2java
 */
@Entity
@Table(name = "table1", catalog = "test")
public class Table1 implements java.io.Serializable {

	private Integer id;
	private String name;

	public Table1() {
	}

	public Table1(String name) {
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
